### ISSUE TITLE
Feature Request: Show a gif to demo app on the READme

### ISSUE THREAD

**Issue by jonherke** [futuristacademy/PathFindingVisualizer#1]
If you take a video and convert it to a gif then embed that into the READme for a more visual how to - would be nice

**Comment by Ramko9999** [comment]
Good idea! I will capture some videos with the controls as well as a video of a cool maze and turn it into a gif tomorrow.

**Comment by Ramko9999** [comment]
Let me know what you think about the new changes to the readme

**Comment by jonherke** [comment]
That looks way way way better!
